# Generated by Django 3.1.1 on 2020-09-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ngo',
            field=models.BooleanField(default=False),
        ),
    ]
