# Generated by Django 3.1.1 on 2020-09-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.CharField(max_length=100),
        ),
    ]
